server:
  port: 8080
zookeeper:
  host: 127.0.0.1:2181
  timeout: 40000
etcd:
  url: http://127.0.0.1:2379
hash:
  nodes: 5 #虚拟节点个数
  path: /hash_consistency
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8 #最大空闲连接
        min-idle: 1 #最小空闲连接
        max-active: 200 #最大连接数
        max-wait: -1 #连接池最大阻塞等待时间 -1 为限制
#两种不同的客户端,这里使用jedis
#    lettuce:
#      pool:
#        max-idle: 8 #最大空闲连接
#        min-idle: 1 #最小空闲连接
#        max-active: 200 #最大连接数
#        max-wait: -1 #连接池最大阻塞等待时间 -1 为限制
    timeout: 3000
logging:
  config: classpath:log4j2.xml
